reference:
  design_bed: "pgx/padd_target_regions/padded_bait_interval.bed"
  fasta: "/data/reference_genomes/hg19/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  fai: "/data/reference_genomes/hg19/BWA_0.7.10_refseq/hg19.with.mt.fai"
  dbsnp: "/data/reference_genomes/dbsnp_138.hg19.vcf"
  target_regions: "data/genomic_regions/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"

haplotypecaller:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--dbsnp /data/reference_genomes/dbsnp_138.hg19.vcf --standard-min-confidence-threshold-for-calling 1.0"