---

resources: "config/resources.yaml"
samples: "config/samples.tsv"
units: "config/units.tsv"

default_container: "docker://hydragenetics/common:0.1.9"

padd_target_regions:
  target_regions: "data/genomic_regions/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"
  padding: 100

reference:
  design_bed: "pgx/padd_target_regions/padded_bait_interval.bed"
  fasta: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  fai: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.fai"
  dbsnp: "/mnt/WD1/ref/dbsnp/dbsnp_138.hg19.vcf"
  target_regions: "data/genomic_regions/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"

haplotypecaller:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--dbsnp /mnt/WD1/ref/dbsnp/dbsnp_138.hg19.vcf --standard-min-confidence-threshold-for-calling 1.0"

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

variant_filtration:
  read_ratio: 0.2
  read_depth: 100

variant_annotator:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

detected_variants:
  target_rsid: "data/genomic_regions/target_rsid.bed"

sample_target_list:
  target_rsid: "data/genomic_regions/target_rsid.bed"
  padding: 0

get_padded_baits:
  target_regions: "data/genomic_regions/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"
  padding: 100
  file_format: "list"

depth_of_baits:
  container: "docker://hydragenetics/gatk4:4.2.2.0"