resources: "config/resources.yaml"
samples: "config/samples.tsv"
units: "config/units.tsv"

default_container: "docker://hydragenetics/common:0.3.0"

reference:
  design_bed: "data/genomic_regions/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"
  design_rsid: "data/genomic_regions/target_rsid.bed"
  fasta: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  fai: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fai"
  dbsnp: "/data/ref_genomes/hg19/variation/dbsnp_138.vcf.gz"

get_padded_bed:
  padding: 100

haplotypecaller:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--dbsnp /data/ref_genomes/hg19/variation/dbsnp_138.vcf.gz --standard-min-confidence-threshold-for-calling 1.0"

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

snv_indels_haplotypecaller:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

variant_filtration:
  read_ratio: 0.2
  read_depth: 100

variant_annotator:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

detected_variants:
  file_type: "VCF"

sample_target_list:
  padding: 0

get_padded_baits:
  padding: 100
  file_format: "list"

depth_of_baits:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--output-format TABLE"

depth_of_targets:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--output-format TABLE"

append_id_to_gdf:
  file_type: "GDF"

get_clinical_guidelines:
  haplotype_definitions: "data/haplotypes/haplotype_definitions.csv"
  haplotype_activity: "data/guidelines/haplotype_activity_score.csv"
  clinical_guidelines: "data/guidelines/clinical_guidelines.csv"
  hidden_haplotypes: "data/haplotypes/hidden_haplotypes.csv"

get_interaction_guidelines:
  interaction_guidelines: "data/guidelines/interaction_guidelines.csv"

generate_pgx_report:
  analyzed_variants: "data/haplotypes/analyzed_variants.txt"
