---

resources: "config/resources.yaml"
samples: "config/samples.tsv"
units: "config/units.tsv"

default_container: "docker://hydragenetics/common:0.1.9"

padd_target_regions:
  target_regions: "data/genomic_regions/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"
  padding: 100

get_padded_bed:
  target_regions: "data/genomic_regions/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"
  padding: 100

reference:
  design_bed: "pgx/padd_target_regions/padded_bait_interval.bed"
  fasta: "/data/reference_genomes/hg19/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  fai: "/data/reference_genomes/hg19/BWA_0.7.10_refseq/hg19.with.mt.fai"
  dbsnp: "/data/reference_genomes/dbsnp_138.hg19.vcf"
  target_regions: "data/genomic_regions/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"

haplotypecaller:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--dbsnp /data/reference_genomes/dbsnp_138.hg19.vcf --standard-min-confidence-threshold-for-calling 1.0"

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

variant_filtration:
  read_ratio: 0.2
  read_depth: 100

variant_annotator:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

detected_variants:
  target_rsid: "data/genomic_regions/target_rsid.bed"
  file_type: "VCF"

sample_target_list:
  target_rsid: "data/genomic_regions/target_rsid.bed"
  padding: 0

get_padded_baits:
  target_regions: "data/genomic_regions/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"
  padding: 100
  file_format: "list"

depth_of_baits:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--output-format TABLE"

depth_of_targets:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--output-format TABLE"

get_clinical_guidelines:
  haplotype_definitions: "data/haplotypes/haplotype_definitions.csv"
  haplotype_activity: "data/guidelines/haplotype_activity_score.csv"
  clinical_guidelines: "data/guidelines/clinical_guidelines.csv"
  hidden_haplotypes: "data/haplotypes/hidden_haplotypes.csv"

append_id_to_gdf:
  target_rsid: "data/genomic_regions/target_rsid.bed"
  file_type: "GDF"
