---

resources: "config/resources.yaml"
samples: "config/samples.tsv"
units: "config/units.tsv"

default_container: "docker://hydragenetics/common:0.1.3"

padd_target_regions:
  target_regions: "temp/data/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"
  padding: 100

reference:
  design_bed: "pgx/padd_target_regions/padded_bait_interval.bed"
  fasta: "/data/ref/UCSC_hg19/genome.fa"
  fai: "/data/ref/UCSC_hg19/genome.fa.fai"

haplotypecaller:
  threads: 22
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--dbsnp /data/ref/dbsnp_138.hg19.vcf --standard-min-confidence-threshold-for-calling 1.0"

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"
