resources: "config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.3"

haplotypecaller:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--dbsnp reference/dbsnp_138.sub.vcf.gz --standard-min-confidence-threshold-for-calling 1.0"

padd_target_regions:
  target_regions: "reference/exons_variants_pharmacogenomics.TPMT.bed"
  padding: 100
  container: "docker://hydragenetics/common:0.1.3"

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

snv_indels_haplotypecaller:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

filtering_variant_filtration:
  read_ratio: 0.2
  read_depth: 100
  container: "docker://quay.io/biocontainers/pysam:0.19.1--py310hd89ff4b_0"

annotation_variant_annotator:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

summary_detected_variants:
  target_rsid: "reference/target_rsid.TPMT.bed"

reference:
  design_bed: "reference/exons_variants_pharmacogenomics.TPMT.bed"
  fasta: "reference/hg19.chr6.fasta"
  fai: "reference/hg19.chr6.fasta.fai"
  dbsnp: "reference/dbsnp_138.sub.vcf.gz"